apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: guestbook
    tier: frontend
spec:
  ports:
  - port: {{ .Values.servicePort }}
    targetPort: 80
  selector:
    app: guestbook
    tier: frontend
